#!/usr/bin/env python3

import os
import sys
import random
import time

def main():
    if len(sys.argv) != 2:
        print("Usage: ./minion S", file=sys.stderr)
        sys.exit(1)

    try:
        S = int(sys.argv[1])
        if S < 0:
            raise ValueError()
    except ValueError:
        print("Error: S must be a non-negative integer.", file=sys.stderr)
        sys.exit(1)

    pid = os.getpid()
    ppid = os.getppid()

    print(f"Minion[{pid}]: created. Parent PID {ppid}.")
    time.sleep(S)

    status = random.choice([0, 1])
    print(f"Child[{pid}]: before terminated. Parent PID {ppid}. Exit status {status}.")
    os._exit(status)


if __name__ == "__main__":
    main()
